### ISSUE TITLE
feature request: move user configuration directory from ${HOME} to the XDG standard ${HOME}/.config

### ISSUE THREAD

**Issue by Corin-EU** [pekwm/pekwm#126]
Would you be prepared to consider moving the user configuration directory "..pekwm" from ${HOME} to the XDG standard directory ${XDG_CONFIG_HOME}, normally ${HOME}/.config, so that it becomes ${HOME}/.config/pekwm?

 Any user data generated by pekwm in future releases would go into ${XDG_DATA_HOME}/pekwm, ie ${HOME}/.local/share/pekwm.

**Comment by pclouds** [comment]
Discussed before: https://github.com/pekdon/pekwm/pull/65

**Comment by Corin-EU** [comment]
Apologies for missing that, but that item has been closed.

In the lastest release v0.2.1 all I see is hardcoded use of the ${HOME} environmental variable (not even a configure @PEKWM_CONFIG_DIR@ variable to be replaced at configuration (and build)  time and no mention of XDG variables whatsoever.

      ./contrib/lobo/pekwm_autoprop.pl:121:   $autoprops_file =~ s/~/$ENV{'HOME'}/;
      ./contrib/lobo/pekwm_autoprop.pl:149:   return $ENV{HOME}."/.pekwm/autoproperties";

     ./contrib/lobo/pekwm_menu_config.pl:305:        $file =~ s/^~/$ENV{'HOME'}/;

     ./data/scripts/pekwm_theme.in:11:LOCAL_THEME_INDEX="$HOME/.pekwm/themes-v1.csv"
     ./data/scripts/pekwm_theme.in:123:    if ! test -e "$HOME/.pekwm"; then
     ./data/scripts/pekwm_theme.in:124:        mkdir -p "$HOME/.pekwm"
     ./data/scripts/pekwm_theme.in:16:SCREENSHOT_CACHE_DIR="$HOME/.cache/pekwm-themes"
     ./data/scripts/pekwm_theme.in:175:    theme_path="$HOME/.pekwm/themes/$1"
     ./data/scripts/pekwm_theme.in:178:# Install theme to $HOME/.pekwm/themes, if activate is given the
     ./data/scripts/pekwm_theme.in:195:         "$HOME/.pekwm/themes" "$theme_path"
     ./data/scripts/pekwm_theme.in:214:    mkdir -p "$HOME/.pekwm/themes_git"
     ./data/scripts/pekwm_theme.in:215:    repo_path="$HOME/.pekwm/themes_git/`echo $theme_remote | tr -cd '[:alnum:]'`"
     ./data/scripts/pekwm_theme.in:218:    ln -sf "$repo_path/$theme_base_path" "$HOME/.pekwm/themes/$theme_name"
     ./data/scripts/pekwm_theme.in:239:# Uninstall theme from $HOME/.pekwm/themes
     ./data/scripts/pekwm_theme.in:656:if test -z "$HOME"; then
     ./data/scripts/pekwm_theme.in:657:    die "\$HOME is not set, can not proceed"

     ./data/scripts/pekwm_themeset.sh.in:52:    theme=`echo "${2}" | @SED@ -e "s@^${HOME}@~@" | @SED@ -e 's@\/@\\\/@g'`

     ./src/Config.cc:1021:   std::string cfg_dir = Util::getEnv("HOME") + "/.pekwm";
     ./src/Config.cc:998:            file = Util::getEnv("HOME") + "/.pekwm/config";

    . /src/pekwm_panel.cc:2775:      std::string panel_config = Util::getEnv("HOME") + "/.pekwm/panel";

      ./src/pekwm_wm.cc:125:                  std::string home = Util::getEnv("HOME");
     ./src/pekwm_wm.cc:128:                                    << "$HOME not set." << std::endl; 

     ./src/Util.cc:382:                              file.replace(0, 1, getEnv("HOME"));

     ./test/system/pekwm.plux:39:    ???failed to get configuration file path, $HOME not set.
     ./test/system/pekwm_theme.plux:55:    !export HOME=$PWD

**Comment by pclouds** [comment]
From that PR

> If a user wants a different location it is possible to use --config or the PEKWM_CONFIG_FILE environment variable, supporting multiple locations can add to confusion.

So no explicit support for XDG. You just run pekwm with the right option. It's possible that pekdon may have changed his mind and accept XDG support out of the box though, I don't know.

**Comment by pekdon** [comment]
Not sure what added value changing this would give to the end user other than manual migration (or automatic moving of files which is an unpleasant experience).

We could of course go with an approach like neovim and others has gone supporting multiple locations, and even falling back to .vimrc if no neovim specific configuration is found.

Major down side with this is that hints, guides etc all point in different directions.

So, if there's some major benefits to be had I'm listening, else I don't think it's worth it.

**Comment by pclouds** [comment]
> Not sure what added value changing this would give to the end user other than manual migration (or automatic moving of files which is an unpleasant experience).

No migration for new installation/users though. No comments on that major down side.

**Comment by Corin-EU** [comment]
If you do not want to change the default configuration directory from ${HOME}/.pekwm to the XDG standard that is your decision and to be respected.

However it should be possible to change the configuration directory at build time (perhaps as well at run time) but because the configuration directory is hardcoded in a number of scripts as ${HOME}/.pekwm  as pointed out above that is not going to work.  And even the method of using the run time variable is not going to work fully because of the hard coding of paths using ${HOME}/.pekwm such as in pekwm_theme, eg

                         LOCAL_THEME_INDEX="$HOME/.pekwm/themes-v1.csv"

                          if ! test -e "$HOME/.pekwm"; then
                         mkdir -p "$HOME/.pekwm"

                         if test "x$2" = "xactivate"; then
                         @CMAKE_INSTALL_PREFIX@/share/pekwm/scripts/pekwm_themeset.sh \
                        "$HOME/.pekwm/themes" "$theme_path"

etc etc

There should be a variable PEKWM_CONFIG_DIRECTORY which defaults to the current ${HOME}/.pekwm (so no change for anybody unless they want it changed)  and this used consistently in the the source code and scripts.  Then at build time, if somebody choses to change it to the $XDG_CONFIG_HOME value, it will be possible and actually work.

**Comment by pekdon** [comment]
Still do not want it configurable at build time (avoids confusion) but fully agree with you on abstracting away the $HOME/.pekwm references!

**Comment by pclouds** [comment]
The C++ code, I'm pretty sure is for fallback only. If you point the config path to elsewhere already then it should never trigger. Those shell scripts like pekwm_theme.in should be fixed. I've been running pekwm with XDG config for a while actually and seen no problem. But lucky(?) for me I didn't use pekwm_theme

**Comment by pekdon** [comment]
Scripts should be working fine now, and starting pekwm without any configuration files copies to the dirname of the provided --config so starting pekwm with --config ~/.config/pekwm/config should work even for new users.
