### ISSUE TITLE
Key bindings persist after removing entry - How To Start Apps?

### ISSUE THREAD

**Issue by 0pLuS0** [pekwm/pekwm#130]
Hello,

I was trying to figure out how I can close all windows with the keys, and I added this in;

Chain = "Q" {   
                        ```KeyPress = "W-Q" { Actions = "Close" }```
                        KeyPress = "Q" { Actions = "Close" }
                        KeyPress = "F" { Actions = "CloseFrame" }
                        KeyPress = "K" { Actions = "Kill" }
                }

After adding in the W-Q line, I then copied /etc/pekwm/keys to /home/user/.pekwm and over wrote it, so I would have the original copy.

After copying the keys file to my HOME, when I restarted pekwm, from the menu option, and I even logged out of X and back into pekwm, the key binding of W-Q still works and closes windows/apps.

I don't understand why the keybinding still persists, when it's no longer there?

I also thought under the External commands section I could add in a line for my file manager spacefm to start, but I can't get it to work, I assumed this was the correct section to add apps to?

Can I use W for the Windows key and combine as W-S?

}
        # External commands
        Chain = "Ctrl Mod4 E" {
                ```KeyPress = "W-S" { Actions = "Exec $TERM" }```
                KeyPress = "E" { Actions = "Exec $TERM" }
                KeyPress = "L" { Actions = "Exec xlock -mode blank" }
                KeyPress = "S" { Actions = "Exec pekwm_screenshot" }
                KeyPress = "C" { Actions = "ShowCmdDialog" }
        }

I also pressed E for the term and nothing happens, and the 'vars' files shows;
$TERM="xterm -fn fixed +sb -bg white -fg black"

THANKS

**Comment by pekdon** [comment]
Many questions in one go here so will try to answer them, will probably miss some.

1. Do not edit /etc/pekwm/* unless you want system wide changes, edit files under ~/.pekwm instead. The files under ~/.pekwm will be loaded instead if they exist.

2. W and - can't be used in the keys file as Windows modifier (this is typically Mod4). Use space instead of - unless you want a literal - press.

So, I'd suggest you restore /etc/pekwm/* to it's original state and then update ~/.pekwm/keys with the bindings you want.

Try adding a binding outside a chain and see if that works for you.

Also, if you have not already read through the documentation if you want pointers on how to configure.

If you have, pointers on improving it making it easier to understand is much appreciated.

**Comment by 0pLuS0** [comment]
Hi @pekdon wow, thanks a lot of a fast reply!

Sorry, I have been reading around, trying to figure things out, it's a bit confusing, especially all the various ```Mod``` and numbers...

I placed at the very top this and it works!

```KeyPress = "Mod4 S" { Actions = "Exec spacefm" }```

But what about the line I added? Before I added this pressing ```Mod 4 Q``` did nothing, windows didn't close.

Chain = "Q" {
```KeyPress = "W-Q" { Actions = "Close" }```

Unless I'm falling a sleep over here LOL, ```Mod4 Q``` is a built in keybinding already by default in pekwm to close windows?

I only noticed two ```Mod```  ```Mod1``` and ```Mod4```, what key is Mod1?

THANKS

**Comment by pekdon** [comment]
From the documentation FAQ

What is Mod1? How about Mod4?

In the ~/.pekwm/keys and ~/.pekwm/mouse there are all these odd Mod1 and Mod4 things used as modifier keys. It's simple - Mod1 is more widely known as the Alt key, and Mod4 as the "windows key" found on recent keyboards. Use xev to find out what names keys carry.

**Comment by 0pLuS0** [comment]
@pekdon 

Is it possible in the keys and menu file to just have a partial path to exec something, instead of having to place in the full /path?

As an example, I have some apps I have running from scripts, and if they live in the users $HOME, then I thought the normal tilde ~/ backslash /path/to/app would be fine, without needing to put in the full path like; /home/user/

So I was trying to do run apps this way, without the full path, but it doesn't work;

```Entry = "Dolphin" { Actions = "Exec ~/.config/dolphin-emu/start.sh" }```

**Comment by pekdon** [comment]
Exec was changed recently not to use the shell. You can change Exec to ShellExec or replace ~ with $_HOME

**Comment by 0pLuS0** [comment]
Sorry for all the questions I'm trying my best here, LOL, I've actually been an Opebox user of many years, so this transition in pekwm is odd for me, and I really appreciate your time! :)

Something else, I would run this cmd in openbox to open up a urxvt term as sudo root, it would also up the term in the roots $HOME

```KeyPress = "Mod4 r" { Actions = "Exec /home/rog/.urxvtcd -T urxvt -e sudo su" }```

When I pressed Mod4 r it opens the term in the users home instead, how can I do this in pekwm to open in the roots home?

Sorry I thought the cmds would be the same for openbox and pekwm... hmm

THANKS

**Comment by 0pLuS0** [comment]
I tried to take a screen shot pressing Alt Print, nothing happens;

```KeyPress = "Mod1 Print" { Actions = "Exec $_PEKWM_SCRIPT_PATH/pekwm_screenshot.sh" }```

THANKS

**Comment by pekdon** [comment]
Try not to enter multiple issues in a single issue as it is hard to keep track when an issue can be closed and wheter or not all questions have been answered. Ok to close this one?

**Comment by 0pLuS0** [comment]
SORRY I closed and reopened, before asking, is ```Mod4 Q``` a default binding built into Pekwm to close windows/apps?

THANKS

**Comment by pekdon** [comment]
Do read the configuration files and documentation, if you can't find the information there feel free to ask.

Joining #pekwm on Libera.Chat is also an option for less formal support.

KeyPress = "Mod4 Q" { Actions = "Close" }

Is in the default keys file.

**Comment by 0pLuS0** [comment]
I'm very SORRY @pekdon I thought I looked over the keys file really good, my mistake...

THANKS
