### ISSUE TITLE
KeyPress = "Mod1 Print" - No Screen Shot - Menu Blank

### ISSUE THREAD

**Issue by 0pLuS0** [pekwm/pekwm#131]
I tried to take a screen shot pressing Alt Print, nothing happens;

```KeyPress = "Mod1 Print" { Actions = "Exec $_PEKWM_SCRIPT_PATH/pekwm_screenshot.sh" }```

But, the menu function works;

```Entry = "Take screenshot" { Actions = "Exec pekwm_screenshot" }``` 

There is an issue when using the menu function, the pekwm menu shows up in the screen shot blank.

![pekwm_screenshot-20220318T205020-1920x1080](https://user-images.githubusercontent.com/36190223/159110891-81098743-b41d-4a4d-91c2-22d580add13c.png)

**Comment by pekdon** [comment]
Assuming you're using a compositor here (the shade on the window), what happens if you stop it? If you change theme, does the menu render corect?

Does pekwm --info output png, jpeg and xpm? Could be a theme with xpm files that fail to load if compiled without xpm support.

I've updated the default keys file to not use pekwm_screenshot.sh, which is no more.

**Comment by 0pLuS0** [comment]
Oh, pekwm_screenshot.sh will be removed in a future update?

THANKS

**Comment by pekdon** [comment]
@0pLuS0 it has already been removed, just missed one instance of it in the configuraiton files.

However, didn't answer my above questions on the theme and how pekwm was compiled.

1. If you are running a compositor, does the menu look any different when it is turned off?
2. What is the output of pekwm --info?

**Comment by 0pLuS0** [comment]
I was using either compton or picom when I was playing around with this, and not sure what you mean, how pekwm was compiled, these are the cmds I used in a build script in Slackware, aka SlackBuild;

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DCMAKE_INSTALL_MANDIR=/usr/man \
    -DCMAKE_BUILD_TYPE=Release ..
  make
  make install DESTDIR=$PKG

 >pekwm --info
pekwm: version 0.3.0
features:  XShape Xinerama Xft image-jpeg image-png image-xpm Xrandr

**Comment by pekdon** [comment]
pekwm is built with all three supported image formats, but I think this likely is a theme issue (outdated theme). Look at your ~/.xsession-errors for hints.

I'm planning on making it more evident to the end user such issues appear.

If you switch theme, menu renders correct?

**Comment by 0pLuS0** [comment]
I was using compton before, but now I'm using Picom, I'm assuming that was the issue, because I'm not seeing this problem.

The screen shot above was taken with the default theme.

Now the menu doesn't even appear when I try it again, so it looks all good.

![pekwm_screenshot-20220320T221526-1920x1080](https://user-images.githubusercontent.com/36190223/159224865-9950876b-4328-4f37-a59f-7c3fff2fa688.png)

**Comment by pekdon** [comment]
So, things are ok now? Or do you mean the menu won't render at all?

If it's ok please do close the issue, if not let me know what it looks like without a composition manager.

**Comment by 0pLuS0** [comment]
Yes it's all good now, I believe the issue was compton, and I've switched to Picom, and I don't see any problems.

I also disabled Picom and it was still good!

THANKS
