### ISSUE TITLE
Question: Taking Screenshots with "bash -c import"?

### ISSUE THREAD

**Issue by 0pLuS0** [pekwm/pekwm#132]
Hello,

How can I use this cmd to take a screen shot with a keybinding added in the keys file?

```bash -c import $_HOME/ScreenShots/screenshot-$(date +%m-%d-%Y).png```

This is how I've been taking screen shots in Linux, I assumed I could make it like;

```KeyPress = "Mod1 Print" { Actions = "Exec bash -c import $_HOME/ScreenShots/screenshot-$(date +%m-%d-%Y).png" }```

THANKS

**Comment by pekdon** [comment]
As pekwm expands variables when parsing the configuration files care has to be taken when having $ in the configuration.

Unable to test at the moment but this should do the trick:
```
KeyPress = "Mod1 Print" { Actions = "Exec bash -c import $_HOME/ScreenShots/screenshot-\$(date +%m-%d-%Y).png" }
```

**Comment by 0pLuS0** [comment]
It doesn't work... :(

Hmm

**Comment by pekdon** [comment]
I'll add some docs on debugging the pekwm configuration when I get time to sit in front of a computer.

**Comment by 0pLuS0** [comment]
Well I just assumed since this is a cmd that works in linux from a terminal, I could just plug it into pekwm

```bash -c "import /home/user/ScreenShots/screenshot-$(date +%m-%d-%Y).png"```

Thanks @pekdon
