### ISSUE TITLE
Question: Sudo Terminal Open in /root/path?

### ISSUE THREAD

**Issue by 0pLuS0** [pekwm/pekwm#133]
I use to run this cmd before in Linux to open up the terminal as root, in the root's $HOME /path.

~/.urxvtcd -T urxvt -e sudo su

I assumed I could run it the same way in pekwm;

```KeyPress = "Mod4 r" { Actions = "Exec $_HOME/.urxvtcd -T urxvt -e sudo su" }```

When I pressed Mod4 r it opens the term as root, but in the users $HOME /path instead.

How can I sudo, open a root terminal in the root's /path?

THANKS

**Comment by pekdon** [comment]
Exec does not support changing the current working directory before executing the command, however executing su with - will do what you want.

```
KeyPress = "Mod4 r" { Actions = "Exec $_HOME/.urxvtcd -T urxvt -e sudo su -" }
```

No plan on adding extra arguments to Exec so closing this issue.

**Comment by 0pLuS0** [comment]
Ahhh why didn't I think of ```su -``` LOL sheesh.

You the MAN, thanks @pekdon sorry for the issue report!
