### ISSUE TITLE
Question: Resize Workspace UI & Menu Title?

### ISSUE THREAD

**Issue by 0pLuS0** [pekwm/pekwm#134]
Hello,

Is there a way to resize or remove the workspace ui?

This thing is huge, and it would be great if I can make it half the size?

![workspace](https://user-images.githubusercontent.com/36190223/159113448-c130a753-06fe-407c-9e57-f7a9a38fb5df.jpg)

I assumed everything for the workspace UI is under this section; (In the theme)

WorkspaceIndicator {

I'm also trying to remove the word ```Workspace``` at the top of the Workspace UI, which is very faint in this theme, and place the number in the center.

Sorry I've really looked through the theme I'm using, I'm not understanding it at this moment.

Also with the menu, how can I get the name ```Pekwm``` to display at the top like the default theme?

![menu](https://user-images.githubusercontent.com/36190223/159113672-9e557496-e8bd-4095-a624-410c3f58f7e0.jpg)

I've attached the theme I'm using...

[theme.txt](https://github.com/pekwm/pekwm/files/8308836/theme.txt)

THANKS @pekdon

**Comment by 0pLuS0** [comment]
SORRY for this post, I found;

ShowWorkspaceIndicator
WorkspaceIndicatorScale

But I still don't know how to remove the name Workspace at the top of the UI, it's very faint to see.

THANKS

**Comment by pekdon** [comment]
There is no configuration available to change the title of the workspace indicator, but what I typically do is define a WorkspaceIndicator decor in the theme fiel and have it set as a border only window not using a title at all.

Look at the default theme for examples.
