### ISSUE TITLE
ShowWorkspaceIndicator = "1" - Flickers On Screen With Tint2

### ISSUE THREAD

**Issue by 0pLuS0** [pekwm/pekwm#136]
Using Slackware 15.0, and  tint2-17.0.1

I have 5 destops in the taskbar of tint2, and I noticed, if I click on them quickly, jumping back and forth between them, the Workspace Indicator UI will slightly flicker on the screen. Sometimes I barely see any of, maybe like only 1/8th of it appears, but today, when I was clicking in tint2, then entire Workspace Indicator appeared on screen with the default theme look, even though I have it disabled in the config file.

This is my config file with is disabled.

INCLUDE = "$_PEKWM_ETC_PATH/config_system"

Files {
    Theme = "~/.pekwm/themes/PekTech"
    ThemeVariant = ""
}

Screen {
    Workspaces = "5"
    WorkspacesPerRow = "0"
    WorkspaceNames = "1;2;3;4;5"
    ShowWorkspaceIndicator = "1"
    ThemeBackground = "False"

    Placement {
        Model = "Centered Smart MouseNotUnder"
    }
}

Here's the tint2rc config I am using.

[tint2rc.txt](https://github.com/pekwm/pekwm/files/8313955/tint2rc.txt)

**Comment by pekdon** [comment]
Set ShowWorkspaceIndicator to 0 if you want to fully disable it, it is now set to be displayed for 1ms.

**Comment by 0pLuS0** [comment]
My mistake, I thought I read in the manual here on Github to set it to 1 to disable.

This is what is written;

```Show WorkspaceIndicator for N milliseconds. If set to < 1, the WorkspaceIndicator is disabled.```

I took that 1 to mean disabled... I wasn't thinking/considering the <...

**Comment by pekdon** [comment]
Changed the wording in the documentation to say 0 explicitly.
