### ISSUE TITLE
Mouse click does not work when pointer is at screen edges

### ISSUE THREAD

**Issue by developer1105** [pekwm/pekwm#142]
When clicking with the mouse, if the cursor is at the top, bottom, left, right, it does not work.

It seems like the mouse is somehow allowed to move to an small area outside the screen limits. 

I use only one monitor and only one workspace. 

Is this a bug or... an alternative configuration is needed?

**Comment by pekdon** [comment]
Added a FAQ entry for this one. Basically add EdgeSize = "0" to the Screen section of your ~/.pekwm/config file and the problem should go away.

**Comment by pclouds** [comment]
configuration.md could use some improvement too. EdgeSize document says "How many pixels from the edge of the screen should screen edges be". Er.. what? There is a ScreenEdge section that describes more, perhaps we can put some explanation there and refer there  for EdgeSize?

**Comment by developer1105** [comment]
Using EdgeSize = "0" works! (when I click on the topmost edge of screen)

There is still a little problem that happens when I click on the bottommost edge of the screen. I am using lxpanel as a bar on the bottom, and I don't know for sure if it has something to do with lxpanel itself or pekwm.
