### ISSUE TITLE
Bad Window Fade With Picom Compositor

### ISSUE THREAD

**Issue by 0pLuS0** [pekwm/pekwm#147]
Hello,

System Specs;
Slackware 15.0
Picom Compositor v9.1 - https://github.com/yshui/picom
nvidia-driver-510.60.02
xorg-server-1.20.14

When closing and minimizing windows, instead of cleanly fading, in pekwm, you can see either flashes of the window, or an image of the window still being displayed before it fades away.

By flashes, what I mean, is if I minimize a big window, firefox, filemanager, gimp, etc., instead of seeing it cleanly fade, behind the window I see a slight flash effect appear on the screen as the window disappears, I hope this make sense. Just look at it like, when a window closes, there's a slight flash effect appearing, for me the color is typically black flashing on the screen quickly before the windows disappear.

With small windows or the pekem menu, I actually see an outline/shadow of that window in black, especially the pekwm menu.

Here's a video of the pekwm menu, notice how you see it appear briefly as black before it disappears.
https://imgur.com/a/GKCHBV4

Here's a video for comparision of the Openbox menu, notice now, how it cleanly disappears with only a fade effect, and no visible black empty menu appear.
https://imgur.com/a/stdfxDW

Here's the picom.conf I am using. (Github won't allow me to attach it even as a .txt extension hmm)

https://dpaste.com/4PGB283A5

THANKS

**Comment by 0pLuS0** [comment]
@pekdon Did you see this issue report?

I just installed 0.3.0 and I still see this.

When I minimize windows, sometimes I'll see an outline of the windows, with a black background.

THANKS

**Comment by 0pLuS0** [comment]
Hi @pekdon I also see this issue with 0.3.1

THANKS

**Comment by pekdon** [comment]
Yep, it's only in the main branch so will be part of 0.4.0
