### ISSUE TITLE
pekwm_panel

### ISSUE THREAD

**Issue by hype3** [pekwm/pekwm#150]
Hi.

I suggest a notification area on pekwm_panel. And some kind of interaction with the open windows on the panel should also be a good thing to have. Nothing happens now when I try to click on the different open windows in the panel.

Is this something on a to-do list or is the pekwm_panel on hold?

**Comment by pekdon** [comment]
So, these are two separate issues and I will create an issue for the notification area (systray support).

As for clicking on the names of the windows should make them focus and raise as it does for me. Do you have any specific CfgDeny autoproperties?

**Comment by pekdon** [comment]
@hype3 #151 is where you can track the progress of the systray support. (When I get around implementing it, hopefully soonish)

**Comment by hype3** [comment]
CfgDeny autoproperties?

Hi.

pekwm is new to me so I haven't change so much in the configs.
