### ISSUE TITLE
[menu] Separator {} issue

### ISSUE THREAD

**Issue by biopsin** [pekwm/pekwm#154]
Running commit https://github.com/pekwm/pekwm/commit/3f364c5d6ebb66a8b5a462584ed317c9319b3a18

For some reason the Separator {} gets rendered in odd ways. Sometimes its ok on root menu but missing on submenues or color flip to white or red and so on. 
![22-09-08--1662624727_scrot](https://user-images.githubusercontent.com/60029989/189072199-bbcc3e2e-26ed-43eb-9cee-1fe1c0438019.png)

Not related to latest commit, I have yet to disect this..

**Comment by pekdon** [comment]
Would you mind sharing the theme this happens with?

**Comment by biopsin** [comment]
It based of minimalist theme, its been workin fine until latetly.
[theme.txt](https://github.com/pekwm/pekwm/files/10288600/theme.txt)

**Comment by pekdon** [comment]
Of course it renders OK for me. I do have ENABLE_SHAPE=ON, would you mind trying with that turned on? I'll try to reproduce some more as well. Does it happen all the time for you?

Good part is that I found a crash bug in the theme data handling using this theme file.

**Comment by biopsin** [comment]
When I compile the release version with my config options it behaves, so I think there is a commit somewhere later that introduces this oddball render.. I will continue digging for it.

**Comment by pekdon** [comment]
A git bisect, not so fun, but would be quite helpful. Does it behave without composition manager? (okraits noticed the drop shadow)

I guess, if you are able to do a bisect however, hopefully will be an easy fix.

**Comment by biopsin** [comment]
It starts here https://github.com/pekwm/pekwm/commit/b7806593993316c60965f167e2bb661f1c0b52da

**Comment by pekdon** [comment]
Of course it had to be, well, might take a bit more time to figure this one out then. But at least I know where to look.

**Comment by biopsin** [comment]
will inpect any changes surounding the MENU_ITEM_SEPARATOR

**Comment by pekdon** [comment]
So, something isn't initialised it seems like then, should narrow it down a bit.

**Comment by pekdon** [comment]
Would you mind trying on trunk again, the rendering code for separators was unused.

**Comment by biopsin** [comment]
Yea that did it, ..lovely facemask btw lol

**Comment by pekdon** [comment]
Marvelous is it not? Daughter did it for herself, no clue what it is supposed to look like, wanted me to try it out and... the result! Hard to beat
