### ISSUE TITLE
manual window placement via window geometry parameter places window at specified Y position minus titlebar height

### ISSUE THREAD

**Issue by Corin-EU** [pekwm/pekwm#162]
Finally upgraded to v0.3.0 and I am still observing a problem with window placement relative to the top of the screen when using the geometry parameter or X resource.

Perhaps I am misunderstanding the Pekwm configuration settings but I have tried to ensure that smart placement is turned off with

              Placement
             {

                      Model   = "Smart"

                     Smart
                     {

                              Column          = "False"
                              Row             = "False"

                              OffsetX         = "0"
                             OffsetY         = "0"

                             LeftToRight     = "False"
                            TopToBottom     = "False"

                     }

           }

If I do 

                             urxvt -geometry 80x25+24+24

 I would expect that the terminal is placed 24 pixels from the top edge of the screen and 24 pixels from the left edge of the screen.   The window is indeed placed 24 pixels to the right of the left edge of the screen but is flush with the top of the screen.  To actually get the window to be placed 24 pixels from the top of the screen, I have to specify a further offset of 24

                            urxvt -geometry 80x25+24+48

24 just happens to be the height of the titlebar.  If I change the titlebar height to say 35, then I have to add on 35 to Y poairion ro  get the window placed at the desired offset from the top of the screen.

With the titlebar height set to 35, and a window launched with urxvt -geometry 80x24+35+35, xwininfo reports

                              Corners:  +35+37  -1065+37  -1065-539  +35-539
                             -geometry 80x25+33+0

If the pekwm configuration is set for a window not to have a titlebar, then the geometry parameter works as expected -- no offset needs to be added to the Y position.

Am I doing something wrong in not effectively turning off smart placement, or is pekwm miscalculating the window Y placement position by the size of the titlebar height?

**Comment by pekdon** [comment]
Have not yet looked into this, but is probably an issue with how the "gravity" is calculated pekwm interpreting this position as a Frame and not Client relative position.

You don't need to disable Smart placement to get the geometry argument to work.

**Comment by pekdon** [comment]
Looked at this and behaves "as expected", the same behavior in multiple window managers.

In pekwm you can use autoproperties to specify clientgeometry for specific windows and will position it relative to the client and will be independent of decors.
