### ISSUE TITLE
ButtonRelase actions on the Client no longer work.

### ISSUE THREAD

**Issue by chrispurnell** [pekwm/pekwm#163]
None of the with modifier actions that are on ButtonRelease events work since 0.3.0.  They worked fine with 0.2.1.

I have it configured so that the Motion actions don't raise the window so I can move a window without raising it. With 0.3.0 I can no longer raise or lower a window by using a modifier and clicking inside the window.  It only works when clicking in the title or border.

**Comment by biopsin** [comment]
I can confirm this on "client" windows, but it works on "root" tho

**Comment by chrispurnell** [comment]
89e6c9515ca6e40336f89520a594068d108e816d was the commit that caused this.

**Comment by biopsin** [comment]
Not entierly convinced this is all, I tried quicly reverting parts of the commit, but could not make ButtonRelease to work, I guess for now there are changes related to this in earlier commits that month..

**Comment by chrispurnell** [comment]
I just needed to revert that first change in Client.cc.

**Comment by biopsin** [comment]
Thats what I tried too, will rebuild and if confirmed it works I can create a PR for it.
