### ISSUE TITLE
Create a theme to promote PekWM

### ISSUE THREAD

**Issue by developer1105** [pekwm/pekwm#166]
I was wondering, it could exist a PekWM theme for IceWM.

This WM (Ice), has many themes related to several operating systems or window managers, like OS/2 Warp, Motif, Windows, WindowMaker, FVWM, Ubuntu, KDE, BeOS, MacOS and others.

If there were a PekWM theme in IceWM, maybe people would feel some curiosity to know PekWM.

I would suggest the orange theme, with three white circles at the right and one white circle at the left.

**Comment by biopsin** [comment]
Who is better to create a lookalike theme in IceWM if not a user of IceWM.. :) so why not create it yourself?
