### ISSUE TITLE
Remove latency of PlaceNew

### ISSUE THREAD

**Issue by xa56b345** [pekwm/pekwm#170]
When opening a new window there's a little latency that make the window show up on the top left of the screen for a second and then apply the PlaceNew value. Would be nice to have no latency and see the window open directly at the correction position 

Preview:
[windowflash.webm](https://github.com/user-attachments/assets/01913660-b51a-4e70-bec3-f5714a782a2b)

**Comment by xa56b345** [comment]
I guess it has to be something related with  initial_frame_order from Client.hh 

```
class State {
        public:
                State(void)
                        : maximized_vert(false),
                          maximized_horz(false),
                          shaded(false),
                          fullscreen(false),
                          placed(false),
                          initial_frame_order(0),
                          skip(0),
                          decor(DECOR_TITLEBAR|DECOR_BORDER),
                          cfg_deny(CFG_DENY_NO)
                {
                }
                ~State(void) { }

                bool maximized_vert, maximized_horz;
                bool shaded;
                bool fullscreen;

                // pekwm states
                bool placed;
                uint initial_frame_order; /**< Initial frame position */
                uint skip, decor, cfg_deny;
        } _state;

```

**Comment by xa56b345** [comment]
Tried the [new-client-on-create](https://github.com/pekwm/pekwm/tree/new-client-on-create) branch

**Comment by xa56b345** [comment]
For peoples experiencing the same issue all you need to do is to undo this particular commit 

https://github.com/pekwm/pekwm/commit/6b0673f29e69659560602d7044ecc9b463397fcd   

Work on pekwm-0.3.0

**Comment by pclouds** [comment]
Interestingly the problem I'm experiencing with https://github.com/ValveSoftware/steam-for-linux/issues/9273 seems to be gone with that commit reverted. Thanks!
