### ISSUE TITLE
Defective padding for the Status window

### ISSUE THREAD

**Issue by ftonneau** [pekwm/pekwm#171]
On my system (Arch with pekwm 0.3.0), writing something like:

    Pad = "T B L R"

in the 

```
Status { 
     ....
} 
```

section of the current theme will work only partially. The first two arguments (T and B, for top and bottom padding in pixels) work as expected, but **the last two arguments** (**L** and **R**, for left and right padding in pixels, I assume) have no effect on the Status Window. 

I have tried with the Default and Winter themes, as well as with my own custom theme: **L** and **R** settings seem to have no effect on the Status window. This window always keeps its default, tiny, L and R padding.

**Comment by pclouds** [comment]
Don't put too much in my words because I really don't know theming / drawing code, but I don't think this has ever worked. Anyway you can try out PR #172 and see if it helps.

**Comment by pekdon** [comment]
Merged @pclouds fix, should be working now @ftonneau.
