### ISSUE TITLE
Discussion - override_redirect set on parent windows

### ISSUE THREAD

**Issue by tycho-kirchner** [pekwm/pekwm#174]
Hi,
A user of my X11 compositing manager [fastcompmgr](https://github.com/tycho-kirchner/fastcompmgr) opened [this issue](https://github.com/tycho-kirchner/fastcompmgr/issues/13) in my repo that "Shadows don't work with PekWM". This happened due to my commit [1b158ec](https://github.com/tycho-kirchner/fastcompmgr/commit/1b158ec2bab7298b7225526fbbd558650e0e3741) where I explicitly excluded *normal* windows from shadows if they have the override_redirect attribute set. Back then, it was a quick fix for Zoom's screen share functionality, which otherwise leads to a huge shadow darkening the whole desktop. Given that according to [Xlib's documentation](https://www.x.org/archive/X11R7.5/doc/libX11/libX11.html)  "window manager clients normally should ignore this window if the override_redirect member is True" I was surprised to see that pekwm, other than openbox, xfwm4, i3, kwin, ... apparently sets this attribute for all parent windows. I briefly changed `params.attr.override_redirect` to `False`  in [src/PDecor.cc::PDecor::createParentWindow](https://github.com/pekwm/pekwm/blob/release-0.3.0/src/PDecor.cc#L259) and apparently things continue to be working, so I'm wondering for the rationale behind setting this to `True`. 
Could you please help me out here? I suppose that either I need a different way to detect Zoom's screen-share window (but I found using override_redirect somewhat "clean" in this context) or maybe pekwm should not set override_redirect on normal windows.

Thanks, Tycho

**Comment by pekdon** [comment]
"I was surprised to see that pekwm, other than openbox, xfwm4, i3, kwin". Does that mean that the other mentioned window managers do NOT set this attribute or that all of them do?

**Comment by tycho-kirchner** [comment]
They do NOT set this attribute on normal windows.

**Comment by tycho-kirchner** [comment]
Openbox, for instance, only sets it for its focus_cycle_indicator, popup windows and a single *netwm support window*.

**Comment by pekdon** [comment]
Good, then that probably should be changed, do not know _why_ it is there but might be an misinterpretation of the spec thinking that the parent window is a window manager window even though it is used for a client.

Worth trying out removing it then. Thanks a lot for the investigation of this issue.

**Comment by tycho-kirchner** [comment]
Your welcome and thanks for trying out. Please note however that I'm no X11 expert, so I'd thoroughly test this before releasing it to the public 🙂. I just posted a question to the [xorg-devel@lists.x.org](mailto:xorg-devel@lists.x.org) mailing list and hope they clarify things up. Meanwhile, in my limited understanding, I think `override_redirect` is used for application developers to tell the window-manager to leave that window alone, doing its thing. Since, for instance, a dock provided by the window manager can be seen as an application itself, it makes perfectly sense to set it to true for the window managers own things. But I see no apparent reason, to intercept [map or configure request](https://tronche.com/gui/x/xlib/window/attributes/override-redirect.html) of normal windows.
