### ISSUE TITLE
Goto Item N in menus does not skip separators

### ISSUE THREAD

**Issue by ftonneau** [pekwm/pekwm#175]
As a follow-up on my previous bug report (issue #161), I have built and installed Pekwm from source (current development branch), and I see that Goto Item N in menus is still buggy. 

Pressing numeric key N in a menu with more than N lines will move the focus to menu line N, whereas previously numeric keys were not working at all -- great.

The problem is that focus will move to line N even if line N contains a separator instead of an actual menu entry. I think that pekwm should rather skip menu separators (as pekwm does with arrow keys), so that if menu line N is a separator, for example, the focus should move to menu line N + 1 (which corresponds to menu entry N).

NB: thanks to the developers for their work on pekwm. Pekwm is fantastic, although sadly underrated. I have also found pekwm_panel to be the best of its kind.

**Comment by pekdon** [comment]
Sorry for being very inactive, work and life has been keeping me quite busy. I'll try to look at it during the weekend!

**Comment by pclouds** [comment]
Hey, good to hear from you!
