### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by CodePagesNet** [pekwm/pekwm#182]
Hi, I'm a new user of pekwm. I like the lightweight simplicity and it's great to see that it's actively engineered!

**Comment by pekdon** [comment]
Great! #pekwm on LibreChat is an option if you want to connect.

Think the unedited issue requested sample configurations, there's nothing official except from the documentation and I run a rather vanilla setup myself.

Anything specific in that would make your setup experience easier?

**Comment by CodePagesNet** [comment]
Hi, thanks much. 

I was running Sway and I like tiling but I was finding that `systemctl suspend` was generally not working -monitor blank but computer fan running and neither kbd nor mouse [pek] would "resume" (only physical reset/power switch resolved (ridiculous). This happened with different Linux distributions (I run Endeavour OS now and like it). Alas, with pekwm the same thing is still happening so it's something more fundamental with power management.

I did find that your default setup is good and appears to provide keyboard access to all pekwm functions so that's the main importance. 

1. I am finding that the closest thing to tiling is the Mod4-G (grow to use free space), is that true? 
2. Can background be set to solid color?
3. Recommend a terminal emulator?

Do you have any interest in supporting wayland? I think that we all have to accept that wayland is becoming the new standard (granted, X11 will probably not be deprecated for a long time).

**Comment by pekdon** [comment]
1. I've updated the default keys file to use a variable for the increments, so to change it using a fresh keys and vars file it is a matter of changing the variable $MOVERESIZE_INCREMENT. It has been bumped from 10 to 15.
2. Yeah, there was a manual-tiling mode by ioerror, never used it myself and didn't hear anyone complain when it was removed. But yeah, grow is what I use.
3. You can disable setting the background from the theme, and then just set it manually, but I'll add a Theme or Background setting to the configuration file for overrides.
4. It is copied on startup to ~/.pekwm/menu so yeah, just edit that.

On not using all space, I would assume that is a terminal with the resize increments set, then it is expected.

And for terminals, I'm boring, using plain xterm and Wayland is not on my radar, quite happy with X11 on OpenBSD.

**Comment by CodePagesNet** [comment]
Yes, I have pekwm 0.3.0 (I use Endeavor OS which uses Arch packages so presumably I have a fairly up-to-date pekwm). I see the delta 10 and I see I can hard code.

This is my main config:

```
INCLUDE = "$_PEKWM_ETC_PATH/config_system"

Files {
    Theme = "/usr/share/pekwm/themes/default-plain"
    ThemeVariant = ""
}

Screen {
    Workspaces = "2"
    WorkspacesPerRow = "1"
    WorkspaceNames = "Main;Utility"

    Placement {
        Model = "CenteredOnParent Smart MouseNotUnder"
    }

    ThemeBackground = "False"
}

Background {
  Texture = "LinesHorz 20% #808080 #808086 #80808c #808092 #808098"
}
```
...  but background not working. I did use "pekwm->Restart" 

Thanks very much for information! (You may have seen my edits about wayland. I'm an early adopter but wayland is too immature and I'm staying with X. I have a good setup I just start pekwm from my .xinitrc and I use alacritty as terminal. I like command  line so I need few menu items and I don't even use status bar panels etc. It's all a distraction to me :-) )

**Comment by pekdon** [comment]
`Background` as part of the configuration file is not YET supported, I will add something like that. It'll be added to pekwm-0.4.0 whenever that will be out.

**Comment by CodePagesNet** [comment]
> And for terminals, I'm boring, using plain xterm and Wayland is not on my radar, quite happy with X11 on OpenBSD.

I set up .Xresources (render font, backspace key etc.) before I switched to alacritty. Not boring, you have discovered the power of simplicity. :-) 

Yes, I have been interested in BSD! But my software package uses Linux and I'm a bit afraid about setup and hardware compatibility. I like the BSD true Unix though and I may port to it.

**Comment by CodePagesNet** [comment]
> `Background` as part of the configuration file is not YET supported, I will add something like that. It'll be added to pekwm-0.4.0 whenever that will be out.

OK, so I just update my local theme if I understand correctly. Impressed with pekwm. It's a good fit for my interests in a window manager. Well done if I may say!

**Comment by CodePagesNet** [comment]
Friendly suggestion: Use more liberal license (e.g. BSD) for config files only, so that users can copy/modify them for local use with pekwm without GPL requirement to document changes etc.

**Comment by pekdon** [comment]
On configuration files: fea2f2617c1c8991dc217a2a1a0408df4dc33c58

**Comment by CodePagesNet** [comment]
I don't want to take advantage so please disregard if you wish, but after "pekwm_theme new" can the default-plain bew included and overridden? Or simply build on the starter theme? (It also created a .config dir with .csv... files - can they be deleted [e.g. if not  creating a theme pkg]?).

**Comment by CodePagesNet** [comment]
"pekwm" "pek" means mouse? My main focus is keyboard but you already have great keyboard support, thanks! Simply adding a vote for keyboard usage :-) Enjoying pekwm! 

HAPPY NEW YEAR!

**Comment by pekdon** [comment]
pekwm is short for pekdon('s) window manager. pekdon is Swedish for pointing device.

If you were to switch over to the GIT version you can now do:

```
Theme {
    BackgroundOverride = "Plain #aaaaaa"
}
```

In ~/.pekwm/config and it will override whatever background is set in the theme.

**Comment by CodePagesNet** [comment]
Interesting to learn a bit of Swedish and have insight into meaning of pekwm!

A note that you and general pekwm user and potential users will probably find helpful. From using "inxi" on Linux to see information, I am fairly certain that pekwm runs on xorg-xwayland! This means that those interested in wayland could also use pekwm wihtout installing a traditional x server. (Xwayland is a compatibility layer on wayland that provides what the original xserver provides).

**Comment by lobre** [comment]
> Wayland is not on my radar, quite happy with X11 on OpenBSD.

@pekdon, may I ask you why Wayland is not picking your interest yet? Is it just that you invested a lot of time writing a window manager on X11 and you are fine with the current situation?

Or you are not convinced with the Wayland approach or level of maturity?

**Comment by CodePagesNet** [comment]
Here is an apropos opinion about X vs Wayland:
https://forum.endeavouros.com/t/recommended-wms/65323/10?u=greg_m

**Comment by pekdon** [comment]
I would say, why scratch if it doesn't itch. There's of course a lot of things that could be better on X11 as well, but works fine, network transparency is a nice touch.
